apiVersion: apps/v1
kind: Deployment
metadata:
  name: onlycoders-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sb-test
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: onlycoders-backend
    spec:
      containers:
        - name: sb-test
          image: gcr.io/PROJECT_ID/IMAGE:TAG
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: neo4j-ce-1-neo4j-secret
            - name: SERVICE
              value: neo4j-ce-1-neo4j-svc
          ports:
            - containerPort: 9000
          resources:
            requests:
              cpu: "100m"
            limits:
              cpu: "1000m"

---
apiVersion: v1
kind: Service
metadata:
  name: onlycoders-backend-service
spec:
  type: LoadBalancer
  ports:
    - port: 9000
      targetPort: 9000
  selector:
    app: onlycoders-backend
