name: Build and Deploy to Antel

on:
  push:
    branches:
      - develop

env:
  FB_SECRET_KEY: ${{ secrets.FB_SECRET_KEY }}

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - uses: danielr1996/envsubst-action@1.0.0
        env:
          VERSION: 1.2.3
          INSTANCE: staging
        with:
          input: src/main/resources/application-prod.properties
          output: src/main/resources/application-prod.properties

      - name: Build with Gradle
        run: |
          echo $FB_SECRET_KEY > src/main/resources/serviceAccount.json
          ./gradlew build
          cp build/libs/backend-0.0.1-SNAPSHOT.jar app.jar

      # - uses: "marvinpinto/action-automatic-releases@latest"
      #   with:
      #     repo_token: "${{ secrets.GITHUB_TOKEN }}"
      #     automatic_release_tag: "latest"
      #     prerelease: true
      #     title: "Development Build"
      #     files: |
      #       build/libs/backend-0.0.1-SNAPSHOT.jar

      - name: rsync deployments
        uses: burnett01/rsync-deployments@4.1
        with:
          switches: -avzr --delete
          path: app.jar
          remote_path: /home/viruscontrol/onlycoders
          remote_host: onlycoders.tech
          remote_user: viruscontrol
          remote_key: ${{ secrets.DEPLOY_KEY }}

      # Deploy the Docker image to the GKE cluster
      - name: Slack Notify
        uses: rtCamp/action-slack-notify@v2.1.3
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
